name: Naz Kamal
favicon: null
layout_spectrum: 0.9541103157680482
typography_spectrum: 0.38715415145270526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d7d7d7'
    - '#606060'
    - '#2d2d2d'
  brandStrength: 0.5848103393800557
  lightness: 0.3109148966614157
  saturation: 0.4778762231580913
  rhythmicContrast: 0.2920995915774256
purpose: []
