name: Naz Kamal
favicon: null
layout_spectrum: 0.9541103157680482
typography_spectrum: 0.38715415145270526
title: Gila Keringat - Keringat Gila
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffcc00'
    - '#000000'
    - '#ffffff'
    - '#4b3807'
    - '#9d8620'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.4778762231580913
  rhythmicContrast: 0.5
purpose: []
